// KCR-3 — first REAL KCR trace. Takes an actual KCR generated by the Command Center
// research queue (not a hand-built one) and drives it through the entire governed
// pipeline in code, persisting to the store, then proves the advanced state survives a
// "refresh" (a fresh read of the persisted store). This is the end-to-end proof that a
// real knowledge change is fully traceable and durable.
import { researchQueueToKCRs } from './researchIntake';
import { syncIntake, upsertKCR, getKCR, clearKCRs, loadKCRs } from './kcrStore';
import { advanceKCR, addEvidence, setProposal, recordReview, publishKCR } from './knowledgeChange';

const ASOF = '2026-07-02';
beforeEach(() => clearKCRs());

describe('first real KCR — research queue → published → survives refresh', () => {
  test('a real generated pricing KCR traces end-to-end and persists', () => {
    // 1. Real intake from the live research queue (deterministic id, command-center source).
    const generated = researchQueueToKCRs(ASOF);
    syncIntake(generated);
    const crabPricing = generated.find((k) => k.assetId === 'Crab Feast' && k.fieldPath === 'purchases[].unitCostRange');
    expect(crabPricing).toBeTruthy();
    expect(crabPricing.createdBy).toBe('command-center');
    expect(crabPricing.type).toBe('citation');
    expect(crabPricing.trigger).toBe('research');
    expect(crabPricing.impact.recommendationEngines).toEqual(expect.arrayContaining(['budget', 'shopping']));
    const id = crabPricing.id;

    // 2. Advance through the governed pipeline (code — publishing UI is parked).
    let k = getKCR(id);                                             // read from the persisted store
    k = advanceKCR(k, 'researching', { asOf: ASOF });
    k = addEvidence(k, { source: 'MD DNR blue-crab market report 2026', sourceType: 'primary', supports: [3, 8] }, ASOF);
    upsertKCR(k);                                                   // persist progress
    k = advanceKCR(k, 'grounded', { asOf: ASOF });
    k = setProposal(k, { newValue: [3, 8], newProvenance: { verificationStatus: 'cited', sources: ['ev-1'] }, verificationStatus: 'cited', rationale: 'DNR report' }, ASOF);
    k = advanceKCR(k, 'review', { asOf: ASOF });
    ['sme', 'editorial', 'governance'].forEach((g) => { k = recordReview(k, g, { by: g, decision: 'approve' }, ASOF); });
    k = advanceKCR(k, 'approved', { by: 'publisher', asOf: ASOF });
    const { kcr: published, version } = publishKCR(k, { prevVersion: 'crab-feast-v-0', versionId: 'crab-feast-v-1', by: 'publisher', asOf: ASOF });
    upsertKCR(published);                                          // persist the published state

    // 3. "Refresh" — a fresh read of the persisted store (what the reloaded Studio sees).
    const reread = getKCR(id);
    expect(reread.status).toBe('published');
    expect(reread.publishedVersion).toBe('crab-feast-v-1');
    expect(reread.evidence).toHaveLength(1);
    expect(reread.proposal.verificationStatus).toBe('cited');
    // Full traceability: insight(created) → evidence → proposal → reviews → published.
    expect(reread.audit.map((a) => a.action)).toEqual(expect.arrayContaining(['created', 'evidence-added', 'proposal-set', 'review:governance', 'published']));
    // The version records the from→to lineage with its trigger.
    expect(version.from).toBeNull();          // research item had no currentValue captured
    expect(version.to).toEqual([3, 8]);
    expect(version.trigger).toBe('research');
    expect(version.supersedes).toBe('crab-feast-v-0');
  });

  test('re-running intake after the advance does NOT regress the published KCR', () => {
    const gen = researchQueueToKCRs(ASOF);
    syncIntake(gen);
    const id = gen.find((k) => k.assetId === 'Crab Feast' && k.fieldPath === 'purchases[].unitCostRange').id;
    let k = getKCR(id);
    k = advanceKCR(k, 'researching', { asOf: ASOF });
    upsertKCR(k);
    // A fresh intake regenerates the SAME gap as a draft — must not clobber progress.
    syncIntake(researchQueueToKCRs(ASOF));
    expect(getKCR(id).status).toBe('researching');
    // And the backlog didn't grow (dedupe by deterministic id).
    const before = loadKCRs().length;
    syncIntake(researchQueueToKCRs(ASOF));
    expect(loadKCRs().length).toBe(before);
  });
});
