// ─── Research Pipeline (KMP-1 Bundle A) ───────────────────────────────────────
// 12-stage research pipeline manifest tracker. The existing campaign system
// tracks campaign STATE (draft → running → kcr). The pipeline manifest tracks
// each of the 12 stages with timestamps and observable outcomes, making the
// full research lifecycle visible.
//
// The pipeline never publishes. It creates and routes KCRs to the existing
// governance queue. Every stage transition is immutable (returns new manifest).
// Nothing here is a store — manifests are persisted by the calling layer.

const KEY = 'ngw-pipeline-manifests';

// ── 12 canonical pipeline stages ─────────────────────────────────────────────
export const PIPELINE_STAGES = [
  'discover',
  'collect',
  'normalize',
  'deduplicate',
  'corroborate',
  'identify-contradictions',
  'generate-findings',
  'generate-kcrs',
  'estimate-impact',
  'assign-reviewers',
  'track-publication',
  'track-validation',
];

export const STAGE_LABELS = {
  'discover':               'Discover',
  'collect':                'Collect',
  'normalize':              'Normalize',
  'deduplicate':            'Deduplicate',
  'corroborate':            'Corroborate',
  'identify-contradictions':'Identify Contradictions',
  'generate-findings':      'Generate Findings',
  'generate-kcrs':          'Generate KCRs',
  'estimate-impact':        'Estimate Impact',
  'assign-reviewers':       'Assign Reviewers',
  'track-publication':      'Track Publication',
  'track-validation':       'Track Validation',
};

export const STAGE_STATUSES = ['pending', 'in-progress', 'complete', 'blocked', 'skipped'];

const slug = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// ── Pipeline manifest factory ─────────────────────────────────────────────────
// A pipeline manifest is the single observable record of a research effort.
// It is created once per research effort and updated (immutably) as stages advance.
export function createPipelineManifest({
  playbookId,
  assetId,
  fieldPath = null,
  campaignId = null,
  gapType = null,
  assignedTo = null,
  at = null,
}) {
  const stages = PIPELINE_STAGES.reduce((m, s) => {
    m[s] = { status: 'pending', startedAt: null, completedAt: null, outcome: null, notes: null };
    return m;
  }, {});

  // Discover is auto-started
  stages.discover.status = 'in-progress';
  stages.discover.startedAt = at;

  return {
    id: `pipe-${slug(playbookId)}-${slug(assetId)}-${String(at || '').slice(0, 10).replace(/-/g, '')}`,
    playbookId,
    assetId,
    fieldPath,
    campaignId,
    gapType,
    assignedTo,
    currentStage: 'discover',
    status: 'active',                 // active | blocked | complete | abandoned
    createdAt: at,
    updatedAt: at,
    stages,
    kcrIds: [],                        // KCRs generated by this pipeline
    evidenceCount: 0,
    findingCount: 0,
    contradictionCount: 0,
    impactEstimate: null,
    completedAt: null,
    audit: [{ at, action: 'created', stage: 'discover' }],
  };
}

// ── Stage advancement (pure — returns new manifest, never mutates) ─────────────
export function advanceStage(manifest, stage, { outcome, notes = null, at = null } = {}) {
  if (!PIPELINE_STAGES.includes(stage)) {
    throw new Error(`Unknown pipeline stage: "${stage}"`);
  }

  const stageIdx = PIPELINE_STAGES.indexOf(stage);
  const nextStage = PIPELINE_STAGES[stageIdx + 1] || null;

  const updatedStages = {
    ...manifest.stages,
    [stage]: {
      ...manifest.stages[stage],
      status: 'complete',
      completedAt: at,
      outcome: outcome || null,
      notes: notes || null,
    },
  };

  if (nextStage) {
    updatedStages[nextStage] = {
      ...updatedStages[nextStage],
      status: 'in-progress',
      startedAt: at,
    };
  }

  return {
    ...manifest,
    currentStage: nextStage || stage,
    status: nextStage ? 'active' : 'complete',
    completedAt: nextStage ? null : at,
    updatedAt: at,
    stages: updatedStages,
    audit: [
      ...(manifest.audit || []),
      { at, action: 'stage-complete', stage, outcome: outcome || null },
      ...(nextStage ? [{ at, action: 'stage-started', stage: nextStage }] : []),
    ],
  };
}

export function blockStage(manifest, stage, reason, at = null) {
  const updatedStages = {
    ...manifest.stages,
    [stage]: {
      ...manifest.stages[stage],
      status: 'blocked',
      notes: reason || 'Blocked — no reason provided',
    },
  };
  return {
    ...manifest,
    status: 'blocked',
    updatedAt: at,
    stages: updatedStages,
    audit: [...(manifest.audit || []), { at, action: 'stage-blocked', stage, reason }],
  };
}

export function skipStage(manifest, stage, reason, at = null) {
  const stageIdx = PIPELINE_STAGES.indexOf(stage);
  const nextStage = PIPELINE_STAGES[stageIdx + 1] || null;
  const updatedStages = {
    ...manifest.stages,
    [stage]: { ...manifest.stages[stage], status: 'skipped', notes: reason || null, completedAt: at },
  };
  if (nextStage) {
    updatedStages[nextStage] = { ...updatedStages[nextStage], status: 'in-progress', startedAt: at };
  }
  return {
    ...manifest,
    currentStage: nextStage || stage,
    updatedAt: at,
    stages: updatedStages,
    audit: [...(manifest.audit || []), { at, action: 'stage-skipped', stage, reason }],
  };
}

export function recordKCR(manifest, kcrId, at = null) {
  return {
    ...manifest,
    kcrIds: [...(manifest.kcrIds || []), kcrId],
    updatedAt: at,
    audit: [...(manifest.audit || []), { at, action: 'kcr-generated', kcrId }],
  };
}

export function setImpactEstimate(manifest, { kcrCount, playbooksAffected, evidenceCount, findingCount, contradictionCount }, at = null) {
  return {
    ...manifest,
    kcrIds: manifest.kcrIds,
    evidenceCount: evidenceCount ?? manifest.evidenceCount,
    findingCount: findingCount ?? manifest.findingCount,
    contradictionCount: contradictionCount ?? manifest.contradictionCount,
    impactEstimate: { kcrCount, playbooksAffected },
    updatedAt: at,
    audit: [...(manifest.audit || []), { at, action: 'impact-estimated', kcrCount, playbooksAffected }],
  };
}

// ── Progress queries (pure) ───────────────────────────────────────────────────
export function getPipelineProgress(manifest) {
  const total = PIPELINE_STAGES.length;
  const completed = PIPELINE_STAGES.filter((s) =>
    manifest.stages[s]?.status === 'complete' || manifest.stages[s]?.status === 'skipped'
  ).length;
  const blocked = PIPELINE_STAGES.some((s) => manifest.stages[s]?.status === 'blocked');
  const pct = Math.round((completed / total) * 100);

  return {
    total,
    completed,
    blocked,
    pct,
    currentStage: manifest.currentStage,
    currentStageLabel: STAGE_LABELS[manifest.currentStage] || manifest.currentStage,
    status: manifest.status,
  };
}

export function getPipelineStatus(manifest) {
  return {
    id: manifest.id,
    playbookId: manifest.playbookId,
    assetId: manifest.assetId,
    fieldPath: manifest.fieldPath,
    status: manifest.status,
    currentStage: manifest.currentStage,
    currentStageLabel: STAGE_LABELS[manifest.currentStage] || manifest.currentStage,
    progress: getPipelineProgress(manifest),
    kcrCount: (manifest.kcrIds || []).length,
    impactEstimate: manifest.impactEstimate,
    createdAt: manifest.createdAt,
    completedAt: manifest.completedAt,
  };
}

// ── Aggregate metrics (Bundle J) ──────────────────────────────────────────────
// Measures research production across many manifests. Derived only — no fabrication.
export function buildPipelineMetrics(manifests = []) {
  if (!manifests.length) {
    return {
      total: 0, active: 0, blocked: 0, complete: 0, abandoned: 0,
      byStage: {}, kcrTotal: 0, evidenceTotal: 0, findingTotal: 0,
      contradictionTotal: 0, avgCompletionPct: 0, stageBottlenecks: [],
    };
  }

  const byStatus = manifests.reduce((m, p) => { m[p.status] = (m[p.status] || 0) + 1; return m; }, {});
  const byStage = manifests.reduce((m, p) => {
    m[p.currentStage] = (m[p.currentStage] || 0) + 1;
    return m;
  }, {});

  const kcrTotal = manifests.reduce((sum, p) => sum + (p.kcrIds || []).length, 0);
  const evidenceTotal = manifests.reduce((sum, p) => sum + (p.evidenceCount || 0), 0);
  const findingTotal = manifests.reduce((sum, p) => sum + (p.findingCount || 0), 0);
  const contradictionTotal = manifests.reduce((sum, p) => sum + (p.contradictionCount || 0), 0);
  const avgCompletionPct = Math.round(
    manifests.reduce((sum, p) => sum + getPipelineProgress(p).pct, 0) / manifests.length
  );

  // Stages where most pipelines are blocked or stuck = bottlenecks
  const stageBottlenecks = Object.entries(byStage)
    .filter(([, count]) => count > 1)
    .sort(([, a], [, b]) => b - a)
    .map(([stage, count]) => ({ stage, label: STAGE_LABELS[stage], count }));

  return {
    total: manifests.length,
    active: byStatus.active || 0,
    blocked: byStatus.blocked || 0,
    complete: byStatus.complete || 0,
    abandoned: byStatus.abandoned || 0,
    byStage,
    kcrTotal,
    evidenceTotal,
    findingTotal,
    contradictionTotal,
    avgCompletionPct,
    stageBottlenecks,
  };
}

// ── Thin localStorage store ───────────────────────────────────────────────────
export function loadManifests() {
  try { return JSON.parse(localStorage.getItem(KEY) || '[]'); } catch { return []; }
}
export function saveManifests(list) {
  try { localStorage.setItem(KEY, JSON.stringify(list || [])); return true; } catch { return false; }
}
export function upsertManifest(manifest) {
  const list = loadManifests();
  const idx = list.findIndex((m) => m.id === manifest.id);
  if (idx >= 0) list[idx] = manifest; else list.push(manifest);
  saveManifests(list);
  return manifest;
}
export function deleteManifest(id) {
  const list = loadManifests().filter((m) => m.id !== id);
  saveManifests(list);
}
export function clearManifests() {
  try { localStorage.removeItem(KEY); } catch { /* noop */ }
}
