// A REAL Airbnb results page, captured 2026-08-05 ─────────────────────────────
// Search: Santa Fe, NM · 2027-06-17 → 2027-06-21 · 10 adults — the exact query
// lodgingSearchLinks() builds for Linda Stewart's 80th. Captured from the live
// rendered page in a browser (their results are JS-rendered, so a server fetch
// returns only the shell — which is precisely why the app asks the host to copy
// the page from her OWN browser).
//
// REDUCED, NOT INVENTED. Each card keeps its real /rooms/ href, its real photo
// URL, and its real text lines in real order — everything tokenStream() reads.
// The ~28KB of Airbnb styling wrapper per card is dropped so this file stays
// readable; nothing that the parser consumes was altered, reordered or written
// by hand. Note the shapes that matter and that no synthetic fixture would have
// guessed: the doubled "6 bedrooms"/"6 bedrooms" lines, the bare "·" and ","
// separators, "Show price breakdown" between the price and its nights, and the
// two Airbnb badge PNGs that ride in place of a listing photo.
export const AIRBNB_SANTA_FE_RESULTS_HTML = `<div><a href="/rooms/742220082744554592"></a><img src="https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-GuestFavorite/original/4d090f93-f9a5-4f06-95e4-ca737c0d0ab5.png"><span>Top guest favorite</span><span>Guest favorite</span><span>Home in Santa Fe</span><span>Mountain views from 6 secluded acres</span><span>4.92 out of 5 average rating, 116 reviews</span><span>4.92 (116)</span><span>,</span><span>·</span><span>6 bedrooms</span><span>6 bedrooms</span><span>,</span><span>·</span><span>9 beds</span><span>9 beds</span><span>,</span><span>·</span><span>5.5 baths</span><span>5.5 baths</span><span>$6,211</span><span>Show price breakdown</span><span>for 4 nights</span><span>$6,211 for 4 nights</span></div>
<div><a href="/rooms/1174846431882101136"></a><img src="https://a0.muscache.com/im/pictures/miso/Hosting-1174846431882101136/original/b01d820a-f6b4-4b5b-8f46-b91cd69150fb.jpeg"><span>Guest favorite</span><span>Guest favorite</span><span>Home in Santa Fe County</span><span>Private backyard with BBQ near the Plaza</span><span>4.95 out of 5 average rating, 101 reviews</span><span>4.95 (101)</span><span>,</span><span>·</span><span>6 bedrooms</span><span>6 bedrooms</span><span>,</span><span>·</span><span>6 beds</span><span>6 beds</span><span>,</span><span>·</span><span>4 baths</span><span>4 baths</span><span>$2,180</span><span>Show price breakdown</span><span>for 4 nights</span><span>$2,180 for 4 nights</span><span>Pay $0 today</span><span>Free cancellation</span></div>
<div><a href="/rooms/1574721869691975245"></a><img src="https://a0.muscache.com/im/pictures/hosting/Hosting-1574721869691975245/original/450bf09b-ce50-47bf-9350-62a08019049b.jpeg"><span>Superhost</span><span>Superhost</span><span>Home in Santa Fe</span><span>Secluded estate with hot tub and views</span><span>5.0 out of 5 average rating, 3 reviews</span><span>5.0 (3)</span><span>,</span><span>·</span><span>5 bedrooms</span><span>5 bedrooms</span><span>,</span><span>·</span><span>10 beds</span><span>10 beds</span><span>,</span><span>·</span><span>3.5 baths</span><span>3.5 baths</span><span>$5,400</span><span>Show price breakdown</span><span>for 4 nights</span><span>$5,400 for 4 nights</span><span>Free cancellation</span></div>
<div><a href="/rooms/1129870673260817461"></a><img src="https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-GuestFavorite/original/4d090f93-f9a5-4f06-95e4-ca737c0d0ab5.png"><span>Top guest favorite</span><span>Guest favorite</span><span>Home in Santa Fe</span><span>Rooftop jacuzzi with panoramic mountain views</span><span>4.95 out of 5 average rating, 88 reviews</span><span>4.95 (88)</span><span>,</span><span>·</span><span>5 bedrooms</span><span>5 bedrooms</span><span>,</span><span>·</span><span>9 beds</span><span>9 beds</span><span>,</span><span>·</span><span>6 baths</span><span>6 baths</span><span>$9,040</span><span>Show price breakdown</span><span>for 4 nights</span><span>$9,040 for 4 nights</span><span>Free cancellation</span></div>
<div><a href="/rooms/663864147212622555"></a><img src="https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-GuestFavorite/original/4d090f93-f9a5-4f06-95e4-ca737c0d0ab5.png"><span>Top guest favorite</span><span>Guest favorite</span><span>Villa in Santa Fe</span><span>Spectacular views from a 5-acre estate</span><span>5.0 out of 5 average rating, 34 reviews</span><span>5.0 (34)</span><span>,</span><span>·</span><span>5 bedrooms</span><span>5 bedrooms</span><span>,</span><span>·</span><span>5 beds</span><span>5 beds</span><span>,</span><span>·</span><span>4 baths</span><span>4 baths</span><span>$4,371</span><span>Show price breakdown</span><span>for 4 nights</span><span>$4,371 for 4 nights</span><span>Pay $0 today</span><span>Free cancellation</span></div>
<div><a href="/rooms/685872797369361569"></a><img src="https://a0.muscache.com/im/pictures/prohost-api/Hosting-685872797369361569/original/6335719f-a707-4e63-99f1-9549da82ccb2.jpeg"><span>Guest favorite</span><span>Guest favorite</span><span>Villa in Santa Fe</span><span>3-unit compound 2 blocks from the Plaza</span><span>5.0 out of 5 average rating, 27 reviews</span><span>5.0 (27)</span><span>,</span><span>·</span><span>7 bedrooms</span><span>7 bedrooms</span><span>,</span><span>·</span><span>11 beds</span><span>11 beds</span><span>,</span><span>·</span><span>6 baths</span><span>6 baths</span><span>$6,984</span><span>Show price breakdown</span><span>for 4 nights</span><span>$6,984 for 4 nights</span><span>Free cancellation</span></div>`;
