// A REAL Google Hotels results page, captured 2026-08-06 ──────────────────────
// Search: "resort spa in Santa Fe, NM Jun 17–Jun 21 for 10 guests" — the exact
// query lodgingSearchLinks() builds for the Hotels door. Captured from the
// live rendered page in a browser, same discipline as the Airbnb/Vrbo
// fixtures: real card markup, real names, real prices, real amenity tags.
//
// THE STRUCTURAL FACT THIS FIXTURE PROVES: every card's <a href> is a Google
// ad-click redirect (/aclk?...&adurl=), not a stable per-hotel URL — unlike
// Airbnb's /rooms/N or Vrbo's /N. There is no canonical hotel link anywhere
// on this page's markup to capture. That is why the Hotels parser this
// fixture backs returns real name/price/rating/amenities but never a url —
// storing the ad redirect as if it were a reopenable link would be the exact
// kind of claim this codebase's own doctrine forbids.
export const GOOGLE_HOTELS_SANTA_FE_RESULTS_HTML = `<li class="fczSu"><a href="/aclk?sa=l&ai=DChsSEwij2ObQi4uWAxXPXEcBHSA-J9UYACICCAEQERoCcXU&co=1&ase=2&gclid=EAIaIQobChMIo9jm0IuLlgMVz1xHAR0gPifVEA0YASABEgIH5vD_BwE&adurl=" target="_blank" rel="noopener noreferrer"><div class="MY0II Aovece"><img src="//lh3.googleusercontent.com/proxy/w39VQ__bgQXS4DOcxqboLiUtOHVbLm9U1JRdAsFyfP9q6ZhKlH9GqAZm1m3ItmMCSdh5inph0hE4xjyDtmI7TMu67g-wl15XUs86y1EvZ7B_RBoc6VJgxxdI52D_koU20EGutt9OZhIU56Y7JMhHsAANfO3UqQ=w472-h352-n-k" alt=""><div class="ujJAIe PxBked"><div class="AdWm1c AFZtd ogfYpf AF5RIe">Ojo Santa Fe Spa Resort</div><div class="UydQr AdWm1c">$365</div><div class="qvZNxc ogfYpf"><span class="pWnpid ogfYpf Dl19bc m6zZ0e"><img src="//www.gstatic.com/travel-hotels/branding/ac238c97-1652-4830-8da8-bb8d8883af88.png" alt="Expedia.com"> Expedia.com</span></div><div class="ny8nsc CQYfx ogfYpf"><span class="ta47le" aria-label="4.2 out of 5 stars from 2,178 reviews" role="img"><span class="oz2bpb bVUOpb"><span class="KFi5wf lA0BZ CQYfx" aria-hidden="true">4.2/5</span><span class="jdzyld XLC8M CQYfx" aria-hidden="true"> (2.2K)</span></span></span><span class="CQYfx ogfYpf"><span aria-hidden="true">&nbsp;·&nbsp;</span>4-star hotel</span></div><div class="ny8nsc CQYfx ogfYpf">Hot tub<span aria-hidden="true">&nbsp;·&nbsp;</span>Spa</div></div></div></a></li>
<li class="fczSu"><a href="/aclk?sa=l&ai=DChsSEwij2ObQi4uWAxXPXEcBHSA-J9UYACICCAEQDRoCcXU&co=1&ase=2&gclid=EAIaIQobChMIo9jm0IuLlgMVz1xHAR0gPifVEA0YBCABEgLNevD_BwE&adurl=" target="_blank" rel="noopener noreferrer"><div class="MY0II Aovece"><img src="//lh3.googleusercontent.com/proxy/fqn3Hnek5ArOQyYX4Epw0ueNc7Vx7DzqFW8-tKQLDUl080NSpQ73e3vBEuVRtZN03HhEUYmN-sAwexQlJ62O-hA24OMhVeJyHsHM-HkeT_TGRDA4_5Ls7QLcCeMDv54v1N-vA_cJRd2W1YMMC_OQF-14Pd0pl3s=w472-h352-n-k" alt=""><div class="ujJAIe PxBked"><div class="AdWm1c AFZtd ogfYpf AF5RIe">Hilton Santa Fe Buffalo Thunder</div><div class="UydQr AdWm1c">$186</div><div class="qvZNxc ogfYpf"><span class="pWnpid ogfYpf Dl19bc m6zZ0e"><img src="//www.gstatic.com/travel-hotels/branding/13332893293245152842.png" alt="Hilton Santa Fe Buffalo Thunder"> Hilton Santa Fe Buffalo Thunder</span></div><div class="ny8nsc CQYfx ogfYpf"><span class="ta47le" aria-label="4.1 out of 5 stars from 4,116 reviews" role="img"><span class="oz2bpb bVUOpb"><span class="KFi5wf lA0BZ CQYfx" aria-hidden="true">4.1/5</span><span class="jdzyld XLC8M CQYfx" aria-hidden="true"> (4.1K)</span></span></span><span class="CQYfx ogfYpf"><span aria-hidden="true">&nbsp;·&nbsp;</span>4-star hotel</span></div><div class="ny8nsc CQYfx ogfYpf">Hot tub<span aria-hidden="true">&nbsp;·&nbsp;</span>Spa</div></div></div></a></li>
<li class="fczSu"><a href="/aclk?sa=l&ai=DChsSEwij2ObQi4uWAxXPXEcBHSA-J9UYACICCAEQDxoCcXU&co=1&ase=2&gclid=EAIaIQobChMIo9jm0IuLlgMVz1xHAR0gPifVEA0YByABEgIJu_D_BwE&adurl=" target="_blank" rel="noopener noreferrer"><div class="MY0II Aovece"><img src="//lh3.googleusercontent.com/proxy/yTNKfkl8SbksJ0xj30Stqvjm-C153ujsmNNntjuHN9x3Htl_YgnWliNNBcpOndAvgxdBYH2TMk5y-WrXO1PSKvdlo_VvFemB4msrEij1TgDHWR74PtpIAuFKMubuRqJ2T4y_hbN4HsxOYOb7jcJ7mcQ-LUNld9c=w472-h352-n-k" alt=""><div class="ujJAIe PxBked"><div class="AdWm1c AFZtd ogfYpf AF5RIe">Four Seasons Resort Rancho Encantado Santa Fe</div><div class="UydQr AdWm1c">$1,457</div><div class="qvZNxc ogfYpf"><span class="pWnpid ogfYpf Dl19bc m6zZ0e"><img src="//www.gstatic.com/travel-hotels/branding/ac238c97-1652-4830-8da8-bb8d8883af88.png" alt="Expedia.com"> Expedia.com</span></div><div class="ny8nsc CQYfx ogfYpf"><span class="ta47le" aria-label="4.6 out of 5 stars from 634 reviews" role="img"><span class="oz2bpb bVUOpb"><span class="KFi5wf lA0BZ CQYfx" aria-hidden="true">4.6/5</span><span class="jdzyld XLC8M CQYfx" aria-hidden="true"> (634)</span></span></span><span class="CQYfx ogfYpf"><span aria-hidden="true">&nbsp;·&nbsp;</span>5-star hotel</span></div><div class="ny8nsc CQYfx ogfYpf">Hot tub<span aria-hidden="true">&nbsp;·&nbsp;</span>Spa</div></div></div></a></li>
<li class="fczSu"><a href="/aclk?sa=l&ai=DChsSEwij2ObQi4uWAxXPXEcBHSA-J9UYACICCAEQAxoCcXU&co=1&ase=2&gclid=EAIaIQobChMIo9jm0IuLlgMVz1xHAR0gPifVEA0YCCABEgIA7PD_BwE&adurl=" target="_blank" rel="noopener noreferrer"><div class="MY0II Aovece"><img src="//lh3.googleusercontent.com/proxy/UrKk5aQYWP5ycB2j6rf15RRs9_hME_g0InJVlMKUG1XftQgB79El8ZGuserajUyOZSGsaKwTiW1grc9q1cyLO0XpaW7Szo6Pk71GBweGW_aPEjYms_Toho6QVbnAWB0WEObaHssOJ6Yb4hRVIDEyWO23pQ3usAI=w472-h352-n-k" alt=""><div class="ujJAIe PxBked"><div class="AdWm1c AFZtd ogfYpf AF5RIe">La Fonda on the Plaza</div><div class="UydQr AdWm1c">$389</div><div class="qvZNxc ogfYpf"><span class="pWnpid ogfYpf Dl19bc m6zZ0e"><img src="//www.gstatic.com/travel-hotels/branding/icon_184.png" alt="Booking.com"> Booking.com</span></div><div class="ny8nsc CQYfx ogfYpf"><span class="ta47le" aria-label="4.5 out of 5 stars from 2,884 reviews" role="img"><span class="oz2bpb bVUOpb"><span class="KFi5wf lA0BZ CQYfx" aria-hidden="true">4.5/5</span><span class="jdzyld XLC8M CQYfx" aria-hidden="true"> (2.9K)</span></span></span><span class="CQYfx ogfYpf"><span aria-hidden="true">&nbsp;·&nbsp;</span>4-star hotel</span></div><div class="ny8nsc CQYfx ogfYpf">Free cancellation<span aria-hidden="true">&nbsp;·&nbsp;</span>Hot tub</div></div></div></a></li>`;
