// ─── THE SAMPLE CORPUS MUST NOT ROT ──────────────────────────────────────────
//
// Absolute dates in the seed files encoded a lead on the day they were written
// and shrank by one every day after. By 2026-07-31 that had put 9 of 21 events
// past their own date — rendering ZERO rows, so half the corpus was silently
// inert — and had walked ev-x-retirement-party from the 43-day lead every Figma
// board was captured at down to 29, breaking the parity check that verifies
// against those boards.
//
// These gates pin the fix from three sides: the seed files must route through
// the rebase, the anchor must keep the corpus alive, and the one event the
// design boards depend on must hold its lead exactly.
import fs from 'fs';
import path from 'path';
import { SAMPLE_EVENTS_EXTRA } from '../../data/sampleEventsExtra';
import { SAMPLE_EVENTS_DMV } from '../../data/sampleEventsDMV';
import { SAMPLE_ANCHOR, rebaseDelta, shiftIso, rebaseSampleEvents } from '../sampleDateRebase';
import { daysUntil } from '../dates';

const SEEDS = ['../../data/sampleEventsExtra.js', '../../data/sampleEventsDMV.js']
  .map((p) => ({ p, src: fs.readFileSync(path.join(__dirname, p), 'utf8') }));

describe('the seed files never export absolute dates', () => {
  test.each(SEEDS.map((s) => [path.basename(s.p), s.src]))(
    '%s keeps its literals raw and exports through the rebase', (_name, src) => {
      // The array literal must NOT be the export — that is what shipped calendar
      // facts straight to the app.
      expect(src).toMatch(/const RAW_SAMPLE_EVENTS_(EXTRA|DMV) = \[/);
      expect(src).toMatch(/export const SAMPLE_EVENTS_(EXTRA|DMV) = rebaseSampleEvents\(RAW_SAMPLE_EVENTS_(EXTRA|DMV)\)/);
      expect(src).toMatch(/import \{ rebaseSampleEvents \} from '\.\.\/lib\/sampleDateRebase'/);
      // No export of a bare array literal, under any name.
      expect(src).not.toMatch(/export const SAMPLE_EVENTS_(EXTRA|DMV) = \[/);
    });

  // The seeds are regenerated by scripts/assembleSampleEvents.js. If that emits a
  // bare export again, the rot returns on the next regeneration and no other test
  // would notice until the boards drifted.
  //
  // THE ASSEMBLER IS GITIGNORED (.gitignore:43), alongside its raw seed sources and
  // the other local-only dev scripts — so it is absent on a fresh clone and in CI.
  // Reading it unconditionally would fail there for a reason that has nothing to do
  // with the invariant. This asserts when the generator is present (the machine that
  // can actually regenerate) and reports absence rather than passing silently.
  test('the assembler emits the wrapper, so regeneration cannot undo this', () => {
    const asmPath = path.join(__dirname, '../../../scripts/assembleSampleEvents.js');
    if (!fs.existsSync(asmPath)) {
      // eslint-disable-next-line no-console
      console.log('[sampleDateRebase] assembler not present (gitignored) — generator gate skipped');
      expect(fs.existsSync(asmPath)).toBe(false);   // an explicit, visible outcome
      return;
    }
    const asm = fs.readFileSync(asmPath, 'utf8');
    expect(asm).toMatch(/RAW_SAMPLE_EVENTS_\$\{BASE\}/);
    expect(asm).toMatch(/rebaseSampleEvents\(RAW_SAMPLE_EVENTS_\$\{BASE\}\)/);
    expect(asm).toMatch(/rebaseImport/);
  });
});

describe('the corpus stays alive wherever the clock is', () => {
  const all = [...SAMPLE_EVENTS_EXTRA, ...SAMPLE_EVENTS_DMV];

  test('every event still carries a readable date', () => {
    expect(all.length).toBeGreaterThan(20);
    for (const e of all) expect(Number.isFinite(daysUntil(e.date))).toBe(true);
  });

  // The authored spread deliberately includes past events (the After stage needs
  // them). What must never happen again is the corpus DRIFTING past-date — the
  // count is a property of the seeds, not of the day the suite runs.
  test('the majority of the corpus is still upcoming', () => {
    const upcoming = all.filter((e) => daysUntil(e.date) >= 0).length;
    expect(upcoming).toBeGreaterThan(all.length / 2);
  });

  test('a run one year from now produces the same leads as today', () => {
    const inAYear = new Date(Date.now() + 365 * 86400000);
    const then = rebaseSampleEvents(SAMPLE_EVENTS_EXTRA.map((e) => ({ id: e.id, date: e.date })), inAYear);
    // Rebasing an already-rebased set shifts by the same delta for every row, so
    // the SPACING between events is invariant — that is the property that rots.
    const gapNow = daysUntil(SAMPLE_EVENTS_EXTRA[1].date) - daysUntil(SAMPLE_EVENTS_EXTRA[0].date);
    const gapThen = daysUntil(then[1].date) - daysUntil(then[0].date);
    expect(gapThen).toBe(gapNow);
  });
});

describe('Figma parity — the boards verify against this event', () => {
  // Every board in file 3jKLC1z1Y0UGWNcenJGDQW reads "43 DAYS · MARGARET'S
  // RETIREMENT". If this number moves, the parity check silently compares two
  // different days and reports the difference as a defect.
  test('ev-x-retirement-party holds the 43-day lead the boards were captured at', () => {
    const ret = SAMPLE_EVENTS_EXTRA.find((e) => e.id === 'ev-x-retirement-party');
    expect(ret).toBeTruthy();
    expect(daysUntil(ret.date)).toBe(43);
  });

  test('its internal obligations keep their authored spacing', () => {
    const ret = SAMPLE_EVENTS_EXTRA.find((e) => e.id === 'ev-x-retirement-party');
    const evDay = daysUntil(ret.date);
    for (const v of ret.vendors || []) {
      if (!v.payDueDate) continue;
      // A payment is due before the event, never after it — the relationship the
      // seeds authored, which a uniform shift preserves by construction.
      expect(daysUntil(v.payDueDate)).toBeLessThanOrEqual(evDay);
    }
  });
});

describe('the shift itself', () => {
  test('anchor is a plain date and a zero delta is a no-op', () => {
    expect(SAMPLE_ANCHOR).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    const onAnchor = new Date(`${SAMPLE_ANCHOR}T12:00:00.000Z`);
    expect(rebaseDelta(onAnchor)).toBe(0);
    const arr = [{ date: '2026-01-01' }];
    expect(rebaseSampleEvents(arr, onAnchor)).toBe(arr);   // identity, not a clone
  });

  test('date-only and instant shapes are both preserved', () => {
    expect(shiftIso('2026-03-01', 1)).toBe('2026-03-02');
    expect(shiftIso('2026-02-28', 1)).toBe('2026-03-01');
    expect(shiftIso('2026-01-01T08:30:00.000Z', 2)).toBe('2026-01-03T08:30:00.000Z');
  });

  // `week` holds template keys the workflow engines match on ("2026-W24",
  // "2026-06 (Wk of Jun 15)"), not moments. Shifting them would break taskRoute
  // and dayAlerts matching, so the matcher is deliberately strict.
  test('week keys and other near-dates are left alone', () => {
    for (const s of ['2026-W24', '2026-06', '2026-06 (Wk of Jun 15)', '2026-06 (4 mo out)', 'someday', '']) {
      expect(shiftIso(s, 5)).toBe(s);
    }
  });

  test('non-strings and odd input never throw', () => {
    for (const bad of [null, undefined, 0, 42, true, {}, []]) {
      expect(() => rebaseSampleEvents(bad)).not.toThrow();
    }
  });
});
